name: laravel package ci dev

on:
  push:
    branches:
      - dev/*

jobs:
  dev:
    uses: knutle/workflows/.github/workflows/laravel-lib-dev.yml@main
    with:
      os: >-
        [ "ubuntu-latest" ]
      php: >-
        [ "8.1" ]
      laravel: >-
        [ "8.*", "9.*" ]
