name: laravel package tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  prod:
    uses: knutle/workflows/.github/workflows/laravel-lib-tagged-release.yml@main
    with:
      os: >-
        [ "ubuntu-latest" ]
      php: >-
        [ "8.0" ]
      laravel: >-
        [ "8.*", "9.*" ]